on: push

jobs:
  cs:
    name: PHP Code Style 😎
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPCS
      run: composer install && ./vendor/bin/phpcs -i && ./vendor/bin/phpcs --standard=WordPress --report=junit --report-file=./build/test-results/report.xml src
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/*.xml'

  md:
    name: PHP Mess Detector 🧹
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: PHPMD
      run: |
        composer install
        ./vendor/bin/phpmd src github cleancode,naming,unusedcode
