on: push

jobs:
  cs:
    name: PHP Code Style 😎
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PHPCS
      run: |
        composer install
        mkdir reports/
        ./vendor/bin/phpcs --standard=WordPress --report=junit --report-file=./reports/report.xml src 
    - name: Test Report
        if: success() || failure()    # run this step even if previous step failed
        with:
          name: PHPCS Results         # Name of the check run which will be created
          path: reports/report.xml    # Path to test results
          reporter: jest-junit        # Format of test results

  md:
    name: PHP Mess Detector 🧹
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: PHPMD
      run: |
        composer install
        ./vendor/bin/phpmd src github cleancode,naming,unusedcode
