on: push

jobs:
  cs:
    name: PHP Code Style 😎
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: PHPCS
      run: |
        composer install
        ./vendor/bin/phpcs --standard=WordPress --report=junit src 

  md:
    name: PHP Mess Detector 🧹
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: PHPMD
      run: |
        composer install
        ./vendor/bin/phpmd src github cleancode,naming,unusedcode 
