on: push

jobs:
  cs:
    name: PHP Code Style 😎
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHPCS
      run: |
        composer install && ./vendor/bin/phpcs --standard=WordPress --report=junit --report-file=./report.xml src &&  cat ./report.xml
    - uses: dorny/test-reporter@v1
      if: success() || failure()        # run this step even if previous step failed
      with:
        name: PHPCS Results         # Name of the check run which will be created
        path: ./report.xml          # Path to test results
        reporter: java-junit        # Format of test results

  md:
    name: PHP Mess Detector 🧹
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2      
    - name: PHPMD
      run: |
        composer install
        ./vendor/bin/phpmd src github cleancode,naming,unusedcode
